#!/bin/bash
fbsetbg -l &
#xrdb "$HOME/.Xresources" &
/usr/lib/notification-daemon-1.0/notification-daemon &
nm-applet &
synclient HorizTwoFingerScroll=1 &
#synclient PalmDetect=1 &
#synclient PalmMinWidth=2 &
redshift-gtk &
(xcalib -c; xcalib -a -gc 0.8) &
#setxkbmap -option compose:menu &
setxkbmap de neo -option -option compose:menu
pactl upload-sample /usr/share/sounds/freedesktop/stereo/bell.oga bell.ogg
pactl load-module module-x11-bell sample=bell.ogg
xset b 100
thunderbird &
kgpg &
export XDG_CURRENT_DESKTOP=GNOME
(xset -dpms; xset s off) &
gnome-terminal -e 'sh -c "nm-online -t 3600 && exec mosh rpi"' &
